name: CI

on:
  push:
    branches: 
      - master

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run build:prod

      - name: Deploy to firebase
        run: |
          ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          CI: true
